plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:3.3.0')

    implementation project(':core')

    // No spring-boot-starter-web — worker has no HTTP server
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
