spring:
  application:
    name: expense-tracker-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/expense_db}
    username: ${DB_USERNAME}
    password: ${DB_APP_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

  flyway:
    url: ${DB_URL}
    user: ${DB_SUPERUSER_USERNAME}
    password: ${DB_PASSWORD}
    enabled: true
    baseline-on-migrate: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiry-days: 7

springdoc:
  swagger-ui:
    path: /swagger-ui.html