spring:
  application:
    name: expense-tracker-api
  
  # Step 3: Database configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/expense_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      ddl-auto: validate # Validate the java representation of DB tables don't drift at run time

  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
